/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.myteam.travelclient;

import TravelApp.Travel;
import TravelApp.place;
import TravelApp.province;
import com.myteam.travel.common.Helper;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author uoc
 */
public class travelList extends javax.swing.JPanel {

    Travel travelImpl;

    /**
     * Creates new form travelList
     */
    public travelList(Travel travelImpl) {
        initComponents();

        this.travelImpl = travelImpl;

        loadData();
        loadGrid();
    }

    private void loadData() {

        province[] provinces = travelImpl.showAllProvince();
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        model.removeAllElements();

        model.addElement(new ComboKeyValue("ALL", ""));
        for (province item : provinces) {
            model.addElement(new ComboKeyValue(item.getProvince(), String.valueOf(item.getId_province())));
        }

        cbxProvince.setModel(model);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        gridData = new javax.swing.JTable();
        cbxProvince = new javax.swing.JComboBox<>();
        btnSearch = new javax.swing.JButton();

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel2.setText("QUẢN LÝ ĐỊA ĐIỂM DU LỊCH");

        jLabel1.setText("Tỉnh");

        gridData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tên địa điểm", "Số điện thoại", "Địa chỉ", "Giới thiệu"
            }
        ));
        jScrollPane1.setViewportView(gridData);

        cbxProvince.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnSearch.setText("Tìm kiếm");
        btnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchMouseClicked(evt);
            }
        });
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxProvince, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearch)))
                .addContainerGap(140, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbxProvince, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    private void btnSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseClicked
        // TODO add your handling code here:
        loadGrid();
    }//GEN-LAST:event_btnSearchMouseClicked

    private void loadGrid() {
        int idProvince = 0;
        ComboKeyValue itemSelected = (ComboKeyValue) cbxProvince.getSelectedItem();
        String province = itemSelected.getValue();

        if (!"".equals(province)) {
            if (Helper.TryParseInt(province) != null) {
                idProvince = Helper.TryParseInt(province);
            }
        }
        place[] places = travelImpl.find(idProvince);
        DefaultTableModel model = (DefaultTableModel) gridData.getModel();
        model.setRowCount(0);
        for (place item : places) {

            Object[] obj = {item.getName(), item.getPhone(), item.getAdress(), item.getInfor()};
            model.addRow(obj);

        }
        gridData.setModel(model);
    }

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cbxProvince;
    private javax.swing.JTable gridData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
