module TravelApp
{
    interface Travel
    {
        string login(in string userName, in string pwd);
        long register(in string userName, in string pwd);
        long add(in string placeName, in string phone, in string address, in string info, in long idProvince);
        long delete(in long id);
        long update(in long id, in string placeName, in string phone, in string address, in string info, in long idProvince);
        string find(in long idProvince);
        oneway void shutdown();
    };
};