module TravelApp
{
    struct place {
    	long id_place;
    	string name;
        string phone;
        string adress;
        string infor;
        long id_province; 
    };
    struct province {
    	long id_province;
    	string province;
    };
    typedef sequence<province> provinceSeq;
    typedef sequence<place> placeSeq;
    interface Travel
    {
        boolean add(in string placeName, in string phone, in string address, in string info, in long idProvince);
        boolean delete(in long id);
        boolean update(in long id, in string placeName, in string phone, in string address, in string info, in long idProvince);
        province findProvince();
        place findPlaceFromName(in string name);
        placeSeq queryPlace(in string placeName);
        provinceSeq showAllProvince ();
        boolean addProvince(in long _id_province,in string _province);
        boolean DelProvince(in long _id_province);
        placeSeq find(in long idProvince);
    };
};