package TravelApp;


/**
* TravelApp/place.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Travel.idl
* Thursday, November 17, 2022 1:12:54 AM ICT
*/

public final class place implements org.omg.CORBA.portable.IDLEntity
{
  public int id_place = (int)0;
  public String name = null;
  public String phone = null;
  public String adress = null;
  public String infor = null;
  public int id_province = (int)0;

  public place ()
  {
  } // ctor

  public place (int _id_place, String _name, String _phone, String _adress, String _infor, int _id_province)
  {
    id_place = _id_place;
    name = _name;
    phone = _phone;
    adress = _adress;
    infor = _infor;
    id_province = _id_province;
  } // ctor

} // class place
