package TravelApp;


/**
* TravelApp/placeSeqHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Travel.idl
* Thursday, November 17, 2022 2:58:05 AM ICT
*/

public final class placeSeqHolder implements org.omg.CORBA.portable.Streamable
{
  public TravelApp.place value[] = null;

  public placeSeqHolder ()
  {
  }

  public placeSeqHolder (TravelApp.place[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TravelApp.placeSeqHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TravelApp.placeSeqHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TravelApp.placeSeqHelper.type ();
  }

}
