package TravelApp;


/**
* TravelApp/placeSeqHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Travel.idl
* Thursday, November 17, 2022 2:58:05 AM ICT
*/

abstract public class placeSeqHelper
{
  private static String  _id = "IDL:TravelApp/placeSeq:1.0";

  public static void insert (org.omg.CORBA.Any a, TravelApp.place[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static TravelApp.place[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = TravelApp.placeHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (TravelApp.placeSeqHelper.id (), "placeSeq", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static TravelApp.place[] read (org.omg.CORBA.portable.InputStream istream)
  {
    TravelApp.place value[] = null;
    int _len0 = istream.read_long ();
    value = new TravelApp.place[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = TravelApp.placeHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, TravelApp.place[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      TravelApp.placeHelper.write (ostream, value[_i0]);
  }

}
