package TravelApp;

/**
* TravelApp/placeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Travel.idl
* Thursday, November 17, 2022 1:12:54 AM ICT
*/

public final class placeHolder implements org.omg.CORBA.portable.Streamable
{
  public TravelApp.place value = null;

  public placeHolder ()
  {
  }

  public placeHolder (TravelApp.place initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TravelApp.placeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TravelApp.placeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TravelApp.placeHelper.type ();
  }

}
