package TravelApp;


/**
* TravelApp/place.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Travel.idl
* Thursday, November 17, 2022 2:58:05 AM ICT
*/

public final class place implements org.omg.CORBA.portable.IDLEntity
{
  public int id_place = (int)0;
  public String name = null;
  public String phone = null;
  public String adress = null;
  public String infor = null;
  public int id_province = (int)0;

  public place ()
  {
  } // ctor

  public place (int _id_place, String _name, String _phone, String _adress, String _infor, int _id_province)
  {
    id_place = _id_place;
    name = _name;
    phone = _phone;
    adress = _adress;
    infor = _infor;
    id_province = _id_province;
  } // ctor

    public int getId_place() {
        return id_place;
    }

    public void setId_place(int id_place) {
        this.id_place = id_place;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getAdress() {
        return adress;
    }

    public void setAdress(String adress) {
        this.adress = adress;
    }

    public String getInfor() {
        return infor;
    }

    public void setInfor(String infor) {
        this.infor = infor;
    }

    public int getId_province() {
        return id_province;
    }

    public void setId_province(int id_province) {
        this.id_province = id_province;
    }

} // class place
