package TravelApp;


/**
* TravelApp/province.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Travel.idl
* Thursday, November 17, 2022 1:12:54 AM ICT
*/

public final class province implements org.omg.CORBA.portable.IDLEntity
{
  public int id_province = (int)0;
  public String province = null;

  public province ()
  {
  } // ctor

  public province (int _id_province, String _province)
  {
    id_province = _id_province;
    province = _province;
  } // ctor

    public int getId_province() {
        return id_province;
    }

    public void setId_province(int id_province) {
        this.id_province = id_province;
    }

    public String getProvince() {
        return province;
    }

    public void setProvince(String province) {
        this.province = province;
    }

} // class province
