package TravelApp;


/**
* TravelApp/TravelOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Travel.idl
* Tuesday, November 15, 2022 8:05:12 PM ICT
*/

public interface TravelOperations 
{
  String login (String userName, String pwd);
  int register (String userName, String pwd);
  int add (String locationName, String phonenumber, String note);
  int update (int id, String locationName, String phonenumber, String note);
  int delete (int id);
  String find (String locationName);
  void shutdown ();
} // interface TravelOperations
