package TravelApp;


/**
* TravelApp/Travel.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Travel.idl
* Tuesday, November 15, 2022 8:05:12 PM ICT
*/

public interface Travel extends TravelOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Travel
