package TravelApp;


/**
* TravelApp/Travel.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Travel.idl
* Wednesday, November 16, 2022 11:38:38 PM ICT
*/

public interface Travel extends TravelOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Travel
