package TravelApp;


/**
* TravelApp/TravelOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Travel.idl
* Wednesday, November 16, 2022 11:38:38 PM ICT
*/

public interface TravelOperations 
{
  String login (String userName, String pwd);
  int register (String userName, String pwd);
  int add (String placeName, String phone, String address, String info, int idProvince);
  int delete (int id);
  int update (int id, String placeName, String phone, String address, String info, int idProvince);
  String find (int idProvince);
  void shutdown ();
} // interface TravelOperations
