package TravelApp;


/**
* TravelApp/TravelHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Travel.idl
* Tuesday, November 15, 2022 8:05:12 PM ICT
*/

abstract public class TravelHelper
{
  private static String  _id = "IDL:TravelApp/Travel:1.0";

  public static void insert (org.omg.CORBA.Any a, TravelApp.Travel that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static TravelApp.Travel extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (TravelApp.TravelHelper.id (), "Travel");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static TravelApp.Travel read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_TravelStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, TravelApp.Travel value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static TravelApp.Travel narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof TravelApp.Travel)
      return (TravelApp.Travel)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      TravelApp._TravelStub stub = new TravelApp._TravelStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static TravelApp.Travel unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof TravelApp.Travel)
      return (TravelApp.Travel)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      TravelApp._TravelStub stub = new TravelApp._TravelStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
