package TravelApp;


/**
* TravelApp/TravelOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Travel.idl
* Thursday, November 17, 2022 2:58:05 AM ICT
*/

public interface TravelOperations 
{
  boolean add (String placeName, String phone, String address, String info, int idProvince);
  boolean delete (int id);
  boolean update (int id, String placeName, String phone, String address, String info, int idProvince);
  TravelApp.province findProvince ();
  TravelApp.place findPlaceFromName (String name);
  TravelApp.place[] queryPlace (String placeName);
  TravelApp.province[] showAllProvince ();
  boolean addProvince (int _id_province, String _province);
  boolean DelProvince (int _id_province);
  TravelApp.place[] find (int idProvince);
} // interface TravelOperations
