package TravelApp;


/**
* TravelApp/TravelPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Travel.idl
* Thursday, November 17, 2022 1:12:54 AM ICT
*/

public abstract class TravelPOA extends org.omg.PortableServer.Servant
 implements TravelApp.TravelOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("add", new java.lang.Integer (0));
    _methods.put ("delete", new java.lang.Integer (1));
    _methods.put ("update", new java.lang.Integer (2));
    _methods.put ("findProvince", new java.lang.Integer (3));
    _methods.put ("findPlaceFromName", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // TravelApp/Travel/add
       {
         String placeName = in.read_string ();
         String phone = in.read_string ();
         String address = in.read_string ();
         String info = in.read_string ();
         int idProvince = in.read_long ();
         boolean $result = false;
         $result = this.add (placeName, phone, address, info, idProvince);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // TravelApp/Travel/delete
       {
         int id = in.read_long ();
         boolean $result = false;
         $result = this.delete (id);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // TravelApp/Travel/update
       {
         int id = in.read_long ();
         String placeName = in.read_string ();
         String phone = in.read_string ();
         String address = in.read_string ();
         String info = in.read_string ();
         int idProvince = in.read_long ();
         boolean $result = false;
         $result = this.update (id, placeName, phone, address, info, idProvince);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // TravelApp/Travel/findProvince
       {
         TravelApp.province $result = null;
         $result = this.findProvince ();
         out = $rh.createReply();
         TravelApp.provinceHelper.write (out, $result);
         break;
       }

       case 4:  // TravelApp/Travel/findPlaceFromName
       {
         String name = in.read_string ();
         TravelApp.place $result = null;
         $result = this.findPlaceFromName (name);
         out = $rh.createReply();
         TravelApp.placeHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:TravelApp/Travel:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Travel _this() 
  {
    return TravelHelper.narrow(
    super._this_object());
  }

  public Travel _this(org.omg.CORBA.ORB orb) 
  {
    return TravelHelper.narrow(
    super._this_object(orb));
  }


} // class TravelPOA
